version: "3.5"
services:
  mongodb:
    image: mongo
    container_name: meu-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  api: # API - Instância 01
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    # command: bash -c "npm run knex"
    expose:
      - "3333"
    environment:
      - API_PORT=3333

volumes:
  mongodb_data: